sudo: required
services:
  - docker

before_install:
  - docker build -t nextinsas/docker-react -f Dockerfile.dev .

Script:
  - docker run nextinsas/docker-react npm run test -- --coverage
#- docker run -e CI=true nextinsas/docker-react npm run test

language: generic
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$BUCKET"
  region: "$REGION"
  acl: public_read
  skip_cleanup: true